# Generated by Django 5.2.8 on 2025-12-07 14:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_motn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motnshow',
            name='episode_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='relevant_queries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), null=True, size=None),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='season_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='source_id',
            field=models.BigIntegerField(blank=True, help_text='Identifier of the external streaming source (e.g. Netflix)', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserViewInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('viewed_amount', models.SmallIntegerField(blank=True, null=True)),
                ('completion_ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.motnshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'show')},
            },
        ),
    ]
