# Generated by Django 6.0 on 2025-12-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_userviewinteraction_rating_userrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userviewinteraction',
            options={'ordering': ['-last_date', 'id']},
        ),
    ]
