# Generated by Django 6.0 on 2025-12-14 22:04

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_userquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='motnshow',
            name='cast_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='generated_embedding_texts',
            field=models.JSONField(blank=True, default=dict, help_text='The GPT-generated text parts used for specific embeddings (plot, meta, tone, tags).'),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='genre_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='language_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='meta_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='plot_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='tags_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='theme_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='tone_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
